# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be1f2850623943ef4cb4a7069b35b58b5ced3ae7c6b94ba7075a5f7a8c04de7e62e503d2bc5994afc6b4b4358f1a63fe689e84f6da5bb93891fcf1e70be27aa3

test:
  secret_key_base: c0f5202ed72d75442b8b1e2b0722220391d4f69448bee0ed9941944f69f9cc42eac97c2ed6e0259779b1b3e2ace113336e36bb409e8551cb5a56739a75971223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
